services:
  apache:
    build: .docker/apache
    container_name: symfony_apache
    ports:
      - "8000:80"
    volumes:
      - .docker/config/vhosts:/etc/apache2/sites-enabled
      - ./app:/home/wwwroot/app
    depends_on:
      - php
    networks:
      - symfony_network

  mysql:
    image: mysql:8.3
    ports:
      - "3317:3306"
    container_name: symfony_mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: symfony
      MYSQL_USER: symfony
      MYSQL_PASSWORD: symfony
    networks:
      - symfony_network

  php:
    build: .docker/php
    container_name: symfony_php
    volumes:
      - ./app:/home/wwwroot/app
    depends_on:
      - mailhog
      - mysql
    networks:
      - symfony_network

  mailhog:
    image: mailhog/mailhog
    container_name: symfony_mailhog
    ports:
      - "8025:8025"
      - "1025:1025"
    networks:
      - symfony_network

networks:
  symfony_network:
    driver: bridge